[package]
name = "fast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.2"
cairo-rs = "0.14"
fltk-flow = "0.1.2"


[build-dependencies]
fl2rust = "0.4"